apiVersion: v1
kind: Pod
metadata:
  labels:
    app: "helpdesk"
    createId: "{{ uuid }}"
    createdBy: pdectl
    createdByUser: wangqiang
    runByUser: '{{ .CliArgs.String "username" }}'
    runByPdectlVersion: "{{ .CliArgs.App.Version }}"
    runnerAddress: "{{ .RunnerAddress }}"
    createdTime: "{{ .CreatedTime }}"
    pdeVersion: "v0.0.9-rc3"
    useWebEditor: "false"
    webEditorPort: 0
    webEditorType: ""
  name: "helpdesk"
  annotations:
    pdectl.douban.com/exec-cmd: '{{ .CliArgs.String "exec-default-cmd" }}'
spec:
  containers:
    - name: "main"
      env:
        - name: HOSTNAME
          value: "helpdesk-main"
      image: "docker.douban/sa/pde-python-cli:latest-3.12-v2"
      ports:
      volumeMounts:
        # mount code folder
        - mountPath: /home/project/
          name: code
        - mountPath: /root/
          name: userhome
        - mountPath: /var/run/mysqld/
          name: mysql-run
        - mountPath: /fuse:rslave
          name: fuse
        - mountPath: /etc/localtime
          name: etc-localtime
          readOnly: true
        - mountPath: /var/run/nscd/
          name: var-run-nscd
          readOnly: true
      workingDir: /home/project
    - name: mysql
      image: docker.douban/dba/mysql:5.7
      command:
        - /bin/bash
        - -c
      args:
        - sed -i "s/are_correct('mysql'/are_correct('root'/g" /run_mysqld.py && /run_mysqld.py --farm test --set server_id=1 --set port=3306 --set innodb_buffer_pool_size=134217728 --set max_connections=1024 --set max_user_connections=1024 --set log_error=/mysql/logs/error.log --set innodb_log_file_size=64M --set user=root --set innodb_use_native_aio=0
      env:
        - name: HOSTNAME
          value: pde_mysql
      volumeMounts:
        - mountPath: /mysql/
          name: mysql-data-dir
        - mountPath: /var/run/mysqld/
          name: mysql-run
        - mountPath: /mysql/data/
          name: mysql-data
        - mountPath: /mysql/configs/
          name: mysql-data-configs
        - mountPath: /mysql/logs/
          name: mysql-data-logs
        - mountPath: /mysql/ssd/
          name: mysql-data-ssd
        - mountPath: /mysql/tmp/
          name: mysql-data-tmp
      workingDir: /
  restartPolicy: Never
  volumes:
    - hostPath:
        path: '{{ .CliArgs.String "project-dir" }}/.doubanpde/data/mysql/'
        type: DirectoryOrCreate
      name: mysql-data-dir
    - hostPath:
        path: '{{ .CliArgs.String "project-dir" }}/.doubanpde/data/mysql/configs/'
        type: DirectoryOrCreate
      name: mysql-data-configs
    - hostPath:
        path: '{{ .CliArgs.String "project-dir" }}/.doubanpde/data/mysql/data/'
        type: DirectoryOrCreate
      name: mysql-data
    - hostPath:
        path: '{{ .CliArgs.String "project-dir" }}/.doubanpde/data/mysql/logs/'
        type: DirectoryOrCreate
      name: mysql-data-logs
    - hostPath:
        path: '{{ .CliArgs.String "project-dir" }}/.doubanpde/data/mysql/ssd/'
        type: DirectoryOrCreate
      name: mysql-data-ssd
    - hostPath:
        path: '{{ .CliArgs.String "project-dir" }}/.doubanpde/data/mysql/tmp/'
        type: DirectoryOrCreate
      name: mysql-data-tmp
    - hostPath:
        path: '{{ .CliArgs.String "project-dir" }}/.doubanpde/data/mysql/run/'
        type: DirectoryOrCreate
      name: mysql-run
    - hostPath:
        path: '{{ .CliArgs.String "project-dir" }}'
        type: Directory
      name: code
    - hostPath:
        path: '{{ expandEnvVar "$HOME/" }}'
        type: Directory
      name: userhome
    - hostPath:
        path: /fuse
        type: Directory
      name: fuse
    - hostPath:
        path: /etc/localtime
      name: etc-localtime
    - hostPath:
        path: /var/run/nscd/
      name: var-run-nscd
